<a href="https://colab.research.google.com/github/YasaminRhd/Pythonia.init/blob/main/Session%208%20%26%209%20(NeuralNetwork)" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys
from sklearn import preprocessing
#np.set_printoptions(threshold=sys.maxsize)

In [ ]:
dataset = pd.read_csv('bp1.csv')
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [ ]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

#Data imputation and correction

In [ ]:
# from sklearn.impute import SimpleImputer
# imp = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
# imp = imp.fit(x[:,:])
# x[:,:] = imp.transform(x[:,:])

#Encoding strings and labels

In [ ]:
# from sklearn.preprocessing import OrdinalEncoder
# enc = OrdinalEncoder()
# enc = enc.fit(x[:,1])
# x[:,1] = enc.transform(x[:,1])
from sklearn.preprocessing import LabelEncoder
le_country = LabelEncoder()
x[:,1] = le_country.fit_transform(x[:,1])
le_gender = LabelEncoder()
x[:,2] = le_gender.fit_transform(x[:,2])

In [ ]:
# from sklearn.preprocessing import LabelEncoder
# le_country2 = LabelEncoder()
# le_country2 = le_country2.fit(x[:,0])
# x[:,0] = le_country2.transform(x[:,0])
# le_y = LabelEncoder()
# y = le_y.fit_transform(y)


#Neutralizing weight

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("country", OneHotEncoder(), [1])], remainder='passthrough')
x = ct.fit_transform(x)
x = x[:,1:]
x

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

#Splitting train and test data

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)
x_train

array([[0.0, 0.0, 571, ..., 1, 0, 28045.77],
       [0.0, 0.0, 704, ..., 0, 1, 66810.48],
       [0.0, 1.0, 772, ..., 1, 1, 75825.57],
       ...,
       [0.0, 1.0, 560, ..., 0, 0, 128882.66],
       [1.0, 0.0, 547, ..., 1, 0, 67789.99],
       [0.0, 0.0, 797, ..., 0, 0, 125110.02]], dtype=object)

#Scaling the data

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.fit_transform(x_test)
x_test

array([[ 1.73436329, -0.56657212,  0.31446453, ..., -1.55901627,
        -1.03771056, -0.82141368],
       [-0.57658047, -0.56657212,  0.39678644, ...,  0.64143012,
        -1.03771056, -0.679803  ],
       [ 1.73436329, -0.56657212,  1.08623239, ..., -1.55901627,
        -1.03771056, -0.96381456],
       ...,
       [-0.57658047, -0.56657212,  0.01604763, ...,  0.64143012,
         0.96365985,  0.94804517],
       [-0.57658047, -0.56657212, -0.45730333, ..., -1.55901627,
         0.96365985,  0.53289563],
       [-0.57658047,  1.76500038, -0.95123476, ...,  0.64143012,
        -1.03771056, -0.76603013]])

In [ ]:
# from sklearn.preprocessing import Normalizer
# norm = Normalizer()
# x_test = norm.fit_transform(x_test)
# x_test

In [ ]:
# from sklearn.preprocessing import normalize
# norm2 = normalize(x_test)
# norm2

In [ ]:
#X_train length is used for explaning the difinition of batch and epoch in the article
print(len(x_train))
print(len(x_test))

8000
2000


#9th Session



In [ ]:
#explained example
import keras
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf


#neural network skeleton
classifier = Sequential()

#hidden layer 1 - input from input data
classifier.add(Dense(input_shape=(11,), units=6, kernel_initializer='random_uniform', activation='relu'))

#hidden layer 2
classifier.add(Dense(units=10, kernel_initializer='random_uniform', activation='relu'))

#Binary output layer 
classifier.add(Dense(units=1, kernel_initializer='random_uniform', activation='sigmoid'))

classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

classifier.fit(x_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
800/800 [==============================] - 14s 1ms/step - loss: 0.5497 - accuracy: 0.7875
Epoch 2/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4345 - accuracy: 0.7912
Epoch 3/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4197 - accuracy: 0.8073
Epoch 4/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4192 - accuracy: 0.8226
Epoch 5/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4212 - accuracy: 0.8276
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4197 - accuracy: 0.8263
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4190 - accuracy: 0.8276
Epoch 8/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4116 - accuracy: 0.8306
Epoch 9/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4221 - accuracy: 0.8246
Epoch 10/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4235 - accur

#First Try

In [ ]:
import tensorflow as tf
import datetime

!rm -rf ./logs/

%reload_ext tensorboard

# Load the TensorBoard notebook extension
%load_ext tensorboard

#Create Sequential model with Dense layers
classifier = Sequential()

#hidden layer 1 - input from input data
classifier.add(Dense(input_shape=(11,), units=7, kernel_initializer='random_uniform', activation='relu'))

#hidden layer 2
classifier.add(Dense(units=9, kernel_initializer='random_uniform', activation='relu'))

#Binary output layer 
classifier.add(Dense(units=1, kernel_initializer='random_uniform', activation='sigmoid'))

#The compile method configures the model’s learning process
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

log_dir = "logs/firstTry/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

#The fit method does the training in batches
classifier.fit(x_train, y_train, batch_size=5, epochs=150, validation_data=(x_test, y_test), callbacks=[tensorboard_callback])

%tensorboard --logdir logs/firstTry

This cell output is too large and can only be displayed while logged in.


#Second Try

In [ ]:
import tensorflow as tf
import datetime

%reload_ext tensorboard

# Load the TensorBoard notebook extension
%load_ext tensorboard

#Create Sequential model with Dense layers
classifier = Sequential()

#hidden layer 1 - input from input data
classifier.add(Dense(input_shape=(11,), units=8, kernel_initializer='random_uniform', activation='relu'))

#hidden layer 2
classifier.add(Dense(units=10, kernel_initializer='random_uniform', activation='relu'))

#Binary output layer 
classifier.add(Dense(units=1, kernel_initializer='random_uniform', activation='sigmoid'))

#The compile method configures the model’s learning process
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

log_dir = "logs/secondTry/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

#The fit method does the training in batches
classifier.fit(x_train, y_train, batch_size=20, epochs=200, validation_data=(x_test, y_test), callbacks=[tensorboard_callback])

%tensorboard --logdir logs/secondTry

This cell output is too large and can only be displayed while logged in.


#Third Try

In [ ]:
import tensorflow as tf
import datetime

%reload_ext tensorboard

# Load the TensorBoard notebook extension
%load_ext tensorboard

#Create Sequential model with Dense layers
classifier = Sequential()

#hidden layer 1 - input from input data
classifier.add(Dense(input_shape=(11,), units=5, kernel_initializer='random_uniform', activation='relu'))

#hidden layer 2
classifier.add(Dense(units=10, kernel_initializer='random_uniform', activation='relu'))

#Binary output layer 
classifier.add(Dense(units=1, kernel_initializer='random_uniform', activation='sigmoid'))

#The compile method configures the model’s learning process
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

log_dir = "logs/thirdTry/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

#The fit method does the training in batches
classifier.fit(x_train, y_train, batch_size=20, epochs=100, validation_data=(x_test, y_test), callbacks=[tensorboard_callback])

%tensorboard --logdir logs/thirdTry

This cell output is too large and can only be displayed while logged in.


#Forth Try


In [ ]:
import tensorflow as tf
import datetime

%reload_ext tensorboard

# Load the TensorBoard notebook extension
%load_ext tensorboard

#Create Sequential model with Dense layers
classifier = Sequential()

#hidden layer 1 - input from input data
classifier.add(Dense(input_shape=(11,), units=11, kernel_initializer='random_uniform', activation='relu'))

#hidden layer 2
classifier.add(Dense(units=8, kernel_initializer='random_uniform', activation='relu'))

#Binary output layer 
classifier.add(Dense(units=1, kernel_initializer='random_uniform', activation='sigmoid'))

#The compile method configures the model’s learning process
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

log_dir = "logs/forthTry/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

#The fit method does the training in batches
classifier.fit(x_train, y_train, batch_size=20, epochs=200, validation_data=(x_test, y_test), callbacks=[tensorboard_callback])

%tensorboard --logdir logs/forthTry

This cell output is too large and can only be displayed while logged in.


In [ ]:
classifier.summary()

In [ ]:
import tensorflow as tf
import datetime

%reload_ext tensorboard

# Load the TensorBoard notebook extension
%load_ext tensorboard

#Create Sequential model with Dense layers
classifier = Sequential()

#hidden layer 1 - input from input data
classifier.add(Dense(input_shape=(11,), units=13, kernel_initializer='random_uniform', activation='relu'))

#hidden layer 2
classifier.add(Dense(units=8, kernel_initializer='random_uniform', activation='relu'))

#Binary output layer 
classifier.add(Dense(units=1, kernel_initializer='random_uniform', activation='sigmoid'))

#The compile method configures the model’s learning process
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

log_dir = "logs/fifthTry/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

#The fit method does the training in batches
classifier.fit(x_train, y_train, batch_size=None, epochs=100, validation_data=(x_test, y_test), callbacks=[tensorboard_callback])

%tensorboard --logdir logs/fifthTry

This cell output is too large and can only be displayed while logged in.


#Sixth Try

In [ ]:
import tensorflow as tf
import datetime

%reload_ext tensorboard

# Load the TensorBoard notebook extension
%load_ext tensorboard

#Create Sequential model with Dense layers
classifier = Sequential()

#hidden layer 1 - input from input data
classifier.add(Dense(input_shape=(11,), units=20, kernel_initializer='random_uniform', activation='relu'))

#hidden layer 2
classifier.add(Dense(units=10, kernel_initializer='random_uniform', activation='relu'))

#Binary output layer 
classifier.add(Dense(units=1, kernel_initializer='random_uniform', activation='sigmoid'))

#The compile method configures the model’s learning process
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

log_dir = "logs/sixthTry/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

#The fit method does the training in batches
classifier.fit(x_train, y_train, batch_size=10, epochs=100, validation_data=(x_test, y_test), callbacks=[tensorboard_callback])

%tensorboard --logdir logs/sixthTry

This cell output is too large and can only be displayed while logged in.


#Seventh Try

In [ ]:
import tensorflow as tf
import datetime

%reload_ext tensorboard

# Load the TensorBoard notebook extension
%load_ext tensorboard

#Create Sequential model with Dense layers
classifier = Sequential()

#hidden layer 1 - input from input data
classifier.add(Dense(input_shape=(11,), units=12, kernel_initializer='random_uniform', activation='relu'))

#hidden layer 2
classifier.add(Dense(units=3, kernel_initializer='random_uniform', activation='relu'))

#Binary output layer 
classifier.add(Dense(units=1, kernel_initializer='random_uniform', activation='sigmoid'))

#The compile method configures the model’s learning process
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

log_dir = "logs/seventhTry/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

#The fit method does the training in batches
classifier.fit(x_train, y_train, batch_size=None, epochs=100, validation_data=(x_test, y_test), callbacks=[tensorboard_callback])

%tensorboard --logdir logs/seventhTry

This cell output is too large and can only be displayed while logged in.
